"""Render the happy-path planner output into an HTML dashboard via ChartRenderingAgent."""

from __future__ import annotations

import json
import sys
from pathlib import Path

import typer  # type: ignore

from agent_orchestrator.runtime.dashboard_renderer import DashboardRenderer

_SRC_ROOT = Path(__file__).resolve().parents[1]
if str(_SRC_ROOT) not in sys.path:
    sys.path.insert(0, str(_SRC_ROOT))

app = typer.Typer(help="Generate the telco churn dashboard HTML using the happy-path plan result.")

_REPO_ROOT = Path(__file__).resolve().parents[2]
_DEFAULT_DATASET = _REPO_ROOT / "CsvProfilerAgent" / "samples" / "telco_churn_sample.csv"
_DEFAULT_PLAN = _REPO_ROOT / "AgentOrchestrator" / "artifacts" / "telco_churn" / "plan.json"
_DEFAULT_OUTPUT = _DEFAULT_PLAN.with_name("telco_dashboard.html")


def _load_payload(path: Path) -> dict:
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:  # pragma: no cover - defensive
        raise typer.BadParameter(f"Plan JSON is invalid: {exc}") from exc


@app.command()
def render(
    dataset: Path = typer.Option(
        _DEFAULT_DATASET,
        exists=True,
        readable=True,
        help="CSV dataset referenced by the happy-path test (defaults to telco sample).",
    ),
    plan: Path = typer.Option(
        _DEFAULT_PLAN,
        exists=True,
        readable=True,
        help="Planner payload JSON generated by the happy-path test.",
    ),
    out: Path = typer.Option(
        _DEFAULT_OUTPUT,
        help="Destination HTML file. Defaults to artifacts/telco_churn/telco_dashboard.html",
    ),
) -> None:
    payload = _load_payload(plan)
    renderer = DashboardRenderer()
    artifact = renderer.render(dataset, payload)
    if artifact is None:
        raise typer.BadParameter(
            "Dashboard renderer unavailable or plan payload produced no renderable sections."
        )

    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(artifact.html, encoding="utf-8")
    typer.echo(
        f"Dashboard HTML written to {out} with {len(artifact.sections)} rendered sections (skipped: {len(artifact.skipped)})."
    )


if __name__ == "__main__":  # pragma: no cover
    app()
