import { useMemo, useState } from 'react'
import clsx from 'clsx'
import type { UploadMetadata } from '@/types/orchestrator'
import styles from './Uploader.module.css'

type Props = {
  isUploading: boolean
  onUpload: (file: File, metadata: UploadMetadata) => Promise<void> | void
  serverError?: string | null
}

const deriveMetadata = (fileName: string): UploadMetadata => ({
  scenarioName: fileName.replace(/\.csv$/i, '') || 'Agent demo dataset',
  objective: 'Autogenerated by agent',
  notes: '',
})

export const Uploader = ({ isUploading, onUpload, serverError }: Props) => {
  const [selectedFile, setSelectedFile] = useState<File | null>(null)
  const [dragActive, setDragActive] = useState(false)
  const [error, setError] = useState<string | null>(null)

  const handleFile = (file: File | null) => {
    if (!file) return
    if (!file.name.endsWith('.csv')) {
      setError('Please choose a .csv file')
      return
    }
    setError(null)
    setSelectedFile(file)
  }

  const onInputChange = (event: React.ChangeEvent<HTMLInputElement>) => {
    if (!event.target.files?.length) return
    handleFile(event.target.files[0])
  }

  const onDrop = (event: React.DragEvent<HTMLLabelElement>) => {
    event.preventDefault()
    setDragActive(false)
    const file = event.dataTransfer.files?.[0]
    handleFile(file ?? null)
  }

  const onDragOver = (event: React.DragEvent) => {
    event.preventDefault()
    setDragActive(true)
  }

  const onDragLeave = (event: React.DragEvent) => {
    event.preventDefault()
    setDragActive(false)
  }

  const handleSubmit = async (event: React.FormEvent<HTMLFormElement>) => {
    event.preventDefault()
    if (!selectedFile) {
      setError('Upload a CSV to get started')
      return
    }
    setError(null)
    const metadata = deriveMetadata(selectedFile.name)
    await onUpload(selectedFile, metadata)
  }

  const reset = () => {
    setSelectedFile(null)
    setError(null)
  }

  const fileLabel = useMemo(() => {
    if (!selectedFile) return 'Drag & drop or browse for a CSV file'
    return `${selectedFile.name} · ${(selectedFile.size / 1024).toFixed(1)} KB`
  }, [selectedFile])

  return (
    <form className={styles.form} onSubmit={handleSubmit}>
      <label
        className={clsx(styles.dropZone, dragActive && styles.dropZoneActive)}
        onDrop={onDrop}
        onDragOver={onDragOver}
        onDragLeave={onDragLeave}
      >
        <input type="file" accept=".csv" onChange={onInputChange} />
        <strong>{fileLabel}</strong>
        <span>{selectedFile ? 'Ready to orchestrate' : 'Max 5MB · secure upload'}</span>
      </label>

      {error ? <span className={styles.error}>{error}</span> : null}
      {serverError ? <span className={styles.error}>{serverError}</span> : null}

      <div className={styles.actions}>
        <button type="button" className={styles.secondaryButton} onClick={reset}>
          Reset
        </button>
        <button type="submit" className={styles.primaryButton} disabled={isUploading}>
          {isUploading ? 'Uploading…' : 'Generate dashboard'}
        </button>
      </div>

      {selectedFile ? (
        <span className={styles.fileMeta}>
          Last modified: {new Date(selectedFile.lastModified).toLocaleString()}
        </span>
      ) : null}
    </form>
  )
}
