import json
from typing import Dict, Any

# Mock planner: deterministic small plan
# Replace with real SLM call later.

def plan_dashboard(profile_summary: Dict[str, Any]) -> Dict[str, Any]:
    cols = [c["name"] for c in profile_summary.get("schema", [])]
    time_col = next((c for c in cols if "date" in c.lower() or "time" in c.lower()), None)
    metric_col = next((c for c in cols if c.lower() in {"revenue", "amount", "value"}), None)
    # Fallback picks first numeric-like column if metric not found
    if not metric_col:
        metric_col = next((c for c in cols if "id" not in c.lower()), cols[0] if cols else "value")

    plan = {
        "title": "Auto Dashboard (Mock)",
        "description": "Generated by mock planner; replace with SLM output.",
        "priority": "overview",
        "sections": []
    }

    # Timeseries section if time column exists
    if time_col:
        plan["sections"].append({
            "title": "Trend",
            "charts": [
                {
                    "id": "timeseries_metric",
                    "title": f"{metric_col} over time",
                    "type": "line",
                    "query": {
                        "operation": "timeseries_agg",
                        "x": time_col,
                        "y": metric_col,
                        "agg": "sum",
                        "time_grain": "month"
                    },
                    "insight": "Basic trend aggregation."
                }
            ]
        })

    # Distribution section
    plan["sections"].append({
        "title": "Distribution",
        "charts": [
            {
                "id": "metric_distribution",
                "title": f"Distribution of {metric_col}",
                "type": "histogram",
                "query": {
                    "operation": "distribution",
                    "x": metric_col
                },
                "insight": "Histogram gives spread overview."
            }
        ]
    })

    return plan
